import { db } from "./database";
import { randomUUID } from "crypto";

const sampleProducts = [
  {
    brand: "Dell",
    model: "Inspiron 15 5000",
    price: 45990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-1135G7",
    purpose: ["Office", "Student"],
    screenIn: 15.6,
    gpu: "Intel Iris Xe Graphics",
    images: ["https://source.unsplash.com/800x800/?dell,laptop"],
    description: "Perfect all-rounder for everyday computing, office work, and student needs. Reliable performance with good battery life.",
    availability: "In Stock",
  },
  {
    brand: "HP",
    model: "Pavilion Gaming 15",
    price: 72990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "AMD Ryzen 5 5600H",
    purpose: ["Gaming", "Content Creation"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce GTX 1650",
    images: ["https://source.unsplash.com/800x800/?gaming,laptop"],
    description: "Solid gaming laptop with excellent cooling and performance for 1080p gaming. Great for content creators too.",
    availability: "In Stock",
  },
  {
    brand: "Lenovo",
    model: "ThinkPad E14",
    price: 58990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 256,
    cpu: "Intel Core i5-1135G7",
    purpose: ["Business", "Office"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?business,laptop"],
    description: "Legendary ThinkPad reliability and comfort. Perfect for business professionals who value durability.",
    availability: "In Stock",
  },
  {
    brand: "Asus",
    model: "VivoBook 15",
    price: 39990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 256,
    cpu: "AMD Ryzen 5 5500U",
    purpose: ["Student", "Office"],
    screenIn: 15.6,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?asus,laptop"],
    description: "Budget-friendly laptop with modern design. Great for students and light office work.",
    availability: "In Stock",
  },
  {
    brand: "Acer",
    model: "Aspire 5",
    price: 42990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-1135G7",
    purpose: ["Student", "Office"],
    screenIn: 15.6,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?acer,laptop"],
    description: "Value for money laptop with ample storage and good performance for everyday tasks.",
    availability: "In Stock",
  },
  {
    brand: "Apple",
    model: "MacBook Air M2",
    price: 114900,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 256,
    cpu: "Apple M2",
    purpose: ["Content Creation", "Business", "Student"],
    screenIn: 13.6,
    gpu: "Apple M2 GPU",
    images: ["https://source.unsplash.com/800x800/?macbook,laptop"],
    description: "Ultra-portable powerhouse with incredible battery life and stunning display. Perfect for creators and professionals.",
    availability: "In Stock",
  },
  {
    brand: "MSI",
    model: "GF63 Thin",
    price: 65990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-11400H",
    purpose: ["Gaming", "Student"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce GTX 1650",
    images: ["https://source.unsplash.com/800x800/?msi,gaming"],
    description: "Thin and light gaming laptop that doesn't compromise on performance. Great for students who game.",
    availability: "In Stock",
  },
  {
    brand: "Dell",
    model: "XPS 13",
    price: 129990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i7-1250U",
    purpose: ["Business", "Content Creation"],
    screenIn: 13.4,
    gpu: "Intel Iris Xe Graphics",
    images: ["https://source.unsplash.com/800x800/?dell,premium"],
    description: "Premium ultrabook with stunning InfinityEdge display. For professionals who demand the best.",
    availability: "In Stock",
  },
  {
    brand: "HP",
    model: "14s",
    price: 35990,
    ramGb: 4,
    storageType: "SSD",
    storageGb: 256,
    cpu: "Intel Core i3-1115G4",
    purpose: ["Student", "Office"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?hp,laptop"],
    description: "Entry-level laptop for basic computing needs. Perfect for students on a tight budget.",
    availability: "In Stock",
  },
  {
    brand: "Lenovo",
    model: "IdeaPad Gaming 3",
    price: 68990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "AMD Ryzen 5 5600H",
    purpose: ["Gaming"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce GTX 1650",
    images: ["https://source.unsplash.com/800x800/?lenovo,gaming"],
    description: "Budget gaming laptop with solid performance and great thermal management.",
    availability: "In Stock",
  },
  {
    brand: "Asus",
    model: "ROG Strix G15",
    price: 124990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 1024,
    cpu: "AMD Ryzen 7 5800H",
    purpose: ["Gaming", "Content Creation"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce RTX 3060",
    images: ["https://source.unsplash.com/800x800/?rog,gaming"],
    description: "High-performance gaming beast with RGB lighting and premium cooling. For serious gamers.",
    availability: "In Stock",
  },
  {
    brand: "Acer",
    model: "Nitro 5",
    price: 78990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-12500H",
    purpose: ["Gaming", "Student"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce RTX 3050",
    images: ["https://source.unsplash.com/800x800/?nitro,gaming"],
    description: "Popular gaming laptop with excellent value. Ray tracing capable for modern games.",
    availability: "In Stock",
  },
  {
    brand: "Apple",
    model: "MacBook Pro 14 M2 Pro",
    price: 189900,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Apple M2 Pro",
    purpose: ["Content Creation", "Business"],
    screenIn: 14.2,
    gpu: "Apple M2 Pro GPU",
    images: ["https://source.unsplash.com/800x800/?macbook,pro"],
    description: "Professional-grade laptop for video editing, 3D work, and demanding creative tasks. Unmatched performance.",
    availability: "In Stock",
  },
  {
    brand: "Dell",
    model: "Vostro 15 3000",
    price: 48990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 256,
    cpu: "Intel Core i3-1115G4",
    purpose: ["Business", "Office"],
    screenIn: 15.6,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?dell,business"],
    description: "Reliable business laptop with enterprise-grade security features. Built for small businesses.",
    availability: "In Stock",
  },
  {
    brand: "HP",
    model: "Envy 13",
    price: 89990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i7-1255U",
    purpose: ["Content Creation", "Business"],
    screenIn: 13.3,
    gpu: "Intel Iris Xe Graphics",
    images: ["https://source.unsplash.com/800x800/?hp,premium"],
    description: "Sleek and powerful ultraportable with stunning display and long battery life.",
    availability: "In Stock",
  },
  {
    brand: "Lenovo",
    model: "ThinkBook 15",
    price: 52990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "AMD Ryzen 5 5500U",
    purpose: ["Business", "Office"],
    screenIn: 15.6,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?lenovo,business"],
    description: "Modern business laptop with excellent keyboard and collaboration features.",
    availability: "In Stock",
  },
  {
    brand: "Asus",
    model: "ZenBook 14",
    price: 79990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-1240P",
    purpose: ["Business", "Student"],
    screenIn: 14,
    gpu: "Intel Iris Xe Graphics",
    images: ["https://source.unsplash.com/800x800/?zenbook,laptop"],
    description: "Premium ultrabook with elegant design and NumberPad 2.0. Perfect for professionals.",
    availability: "In Stock",
  },
  {
    brand: "Razer",
    model: "Blade 15",
    price: 179990,
    ramGb: 32,
    storageType: "SSD",
    storageGb: 1024,
    cpu: "Intel Core i7-12800H",
    purpose: ["Gaming", "Content Creation"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce RTX 3070 Ti",
    images: ["https://source.unsplash.com/800x800/?razer,gaming"],
    description: "Premium gaming laptop with desktop-class performance. For enthusiasts who want the best.",
    availability: "In Stock",
  },
  {
    brand: "MSI",
    model: "Modern 14",
    price: 54990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-1155G7",
    purpose: ["Business", "Student"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?msi,laptop"],
    description: "Portable business laptop with premium build quality and long battery life.",
    availability: "In Stock",
  },
  {
    brand: "Acer",
    model: "Swift 3",
    price: 62990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "AMD Ryzen 7 5700U",
    purpose: ["Student", "Business"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?acer,swift"],
    description: "Lightweight and powerful laptop for students and professionals on the go.",
    availability: "In Stock",
  },
  {
    brand: "HP",
    model: "Omen 16",
    price: 134990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 1024,
    cpu: "Intel Core i7-12700H",
    purpose: ["Gaming", "Content Creation"],
    screenIn: 16.1,
    gpu: "NVIDIA GeForce RTX 3060",
    images: ["https://source.unsplash.com/800x800/?omen,gaming"],
    description: "Powerful gaming laptop with large display and advanced cooling. For competitive gamers.",
    availability: "In Stock",
  },
  {
    brand: "Dell",
    model: "Latitude 5430",
    price: 94990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i7-1265U",
    purpose: ["Business"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?dell,latitude"],
    description: "Enterprise-grade laptop with military-standard durability and advanced security.",
    availability: "In Stock",
  },
  {
    brand: "Lenovo",
    model: "Yoga Slim 7",
    price: 84990,
    ramGb: 16,
    storageType: "SSD",
    storageGb: 512,
    cpu: "AMD Ryzen 7 5800U",
    purpose: ["Content Creation", "Student"],
    screenIn: 14,
    gpu: null,
    images: ["https://source.unsplash.com/800x800/?lenovo,yoga"],
    description: "Sleek 2-in-1 laptop with vibrant OLED display. Perfect for creative students.",
    availability: "In Stock",
  },
  {
    brand: "Asus",
    model: "TUF Gaming F15",
    price: 69990,
    ramGb: 8,
    storageType: "SSD",
    storageGb: 512,
    cpu: "Intel Core i5-11400H",
    purpose: ["Gaming", "Student"],
    screenIn: 15.6,
    gpu: "NVIDIA GeForce RTX 3050",
    images: ["https://source.unsplash.com/800x800/?tuf,gaming"],
    description: "Durable gaming laptop built to military standards. Great value for budget-conscious gamers.",
    availability: "In Stock",
  },
];

export function seedDatabase() {
  const count = db.prepare("SELECT COUNT(*) as count FROM products").get() as { count: number };

  if (count.count > 0) {
    console.log(`Database already has ${count.count} products. Skipping seed.`);
    return;
  }

  const insertProduct = db.prepare(`
    INSERT INTO products (
      id, brand, model, price, ram_gb, storage_type, storage_gb, 
      cpu, purpose, screen_in, gpu, images, description, availability
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertMany = db.transaction((products) => {
    for (const product of products) {
      insertProduct.run(
        randomUUID(),
        product.brand,
        product.model,
        product.price,
        product.ramGb,
        product.storageType,
        product.storageGb,
        product.cpu,
        JSON.stringify(product.purpose),
        product.screenIn,
        product.gpu,
        JSON.stringify(product.images),
        product.description,
        product.availability
      );
    }
  });

  insertMany(sampleProducts);
  console.log(`Seeded database with ${sampleProducts.length} products`);
}
